package com.avalon.calizer.shared.model


object  LocalizationType {
     const val ANALYZE_ALLFOLLOWERS_TITLE = "analyze_allfollowers_title"
     const val ANALYZE_ALLFOLLOWING_TITLE = "analyze_allfollowing_title"
     const val ANALYZE_NEWFOLLOWERS_TITLE = "analyze_newfollowers_title"
     const val ANALYZE_NOTFOLLOWERS_TITLE = "analyze_notfollowers_title"
     const val ANALYZE_UNFOLLOWERS_TITLE = "analyze_unfollowers_title"
     const val ANALYZE_ANALYZE_TITLE = "analyze_analyze_title"
     const val ANALYZE_STORYANALYZE_TITLE = "analyze_storyanalyze_title"
     const val ANALYZE_ALLPOSTS_TITLE = "analyze_allposts_title"
     const val TUTORIAL_PAGE1_DESC = "tutorial_page1_desc"
     const val TUTORIAL_PAGE2_DESC = "tutorial_page2_desc"
     const val TUTORIAL_PAGE3_DESC = "tutorial_page3_desc"
     const val TUTORIAL_PAGER_SKIPINTRO = "tutorial_pager_skipintro"
     const val TUTORIAL_PAGER_STARTNOW = "tutorial_pager_startnow"
     const val ACCOUNTS_ACCOUNTS_TITLE = "accounts_accounts_title"
     const val ACCOUNTS_ACCOUNTS_ADD = "accounts_accounts_add"
     const val PROFILE_FOLLOWERS_TITLE = "profile_followers_title"
     const val PROFILE_FOLLOWING_TITLE = "profile_following_title"
     const val PROFILE_POSTS_TITLE = "profile_posts_title"
     const val PROFILE_ANALYZE_TITLE = "profile_analyze_title"
     const val PROFILE_PHOTOANALYZE_TITLE = "profile_photoanalyze_title"
     const val PROFILE_NEWFOLLOWERS_TITLE = "profile_newfollowers_title"
     const val PROFILE_LOSTFOLLOWERS_TITLE = "profile_lostfollowers_title"
     const val PROFILE_FACERATE_TITLE = "profile_facerate_title"
     const val PROFILE_POSERATE_TITLE = "profile_poserate_title"
     const val PROFILE_PHOTOCOMP_TITLE = "profile_photocomp_title"
     const val PHOTO_TOOLBAR_TITLE = "photo_toolbar_title"
     const val PHOTO_UPLOAD_TITLE = "photo_upload_title"
     const val PHOTO_UPLOAD_DESC = "photo_upload_desc"
     const val PHOTO_UPLOADBTN_TITLE = "photo_uploadbtn_title"
     const val PHOTO_RESULTFACE_TITLE = "photo_resultface_title"
     const val PHOTO_RESULTPOSE_TITLE = "photo_resultpose_title"
     const val STORY_STORYLIST_TITLE = "story_storylist_title"
     const val STORY_STORYSEARCH_TITLE = "story_storysearch_title"
     const val STORY_ONEFEATURED_TITLE = "story_onefeatured_title"
     const val STORY_NOTFOLLOWWATCH_TITLE = "story_notfollowwatch_title"
     const val STORYVIEWS_SECRETWATCH_TITLE = "storyviews_secretwatch_title"
     const val GENERAL_ENTERUSERNAME_TITLE = "general_enterusername_title"
     const val STORYVIEWS_WATCHSTORY_BTN = "storyviews_watchstory_btn"
     const val STORYVIEWS_ONEFEATURED_TITLE = "storyviews_onefeatured_title"
     const val GENERAL_NOSUCHUSER_TITLE = "general_nosuchuser_title"
     const val GENERAL_CONNOTBEEMTY_TITLE = "general_connotbeemty_title"
     const val GENERAL_GALLERY_PERMISSIONS = "general_gallery_permissions"
     const val GENERAL_OK_UPPERCASE = "general_ok_uppercase"

}